language: python
python: 2.7 
env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=pypy
  - TOX_ENV=flake8
install: pip install tox 
script: 
  - tox -e $TOX_ENV
before_script:
  - mysql -e 'create database amivapi;'
  - python manage.py create_config -c testing -f --db-type mysql --db-user travis --db-host localhost --db-name amivapi --file-dir files --root-mail root@example.com --smtp localhost --forward-dir forwards
branches:
  only:
    - master
